"""initial schema

Revision ID: 21bfea8b488f
Revises: 
Create Date: 2026-09-08 21:28:01.712533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21bfea8b488f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('product_statuses',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('recipes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cooking_time_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['category_name'], ['categories.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_ingredients_category_name'), 'ingredients', ['category_name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'sent_at', name='uq_notifications_owner_sent')
    )
    op.create_table('recommendation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'created_at', name='uq_recommendation_sessions_owner_created')
    )
    op.create_table('storage_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'name', name='uq_storage_places_owner_name')
    )
    op.create_table('user_settings',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('notify_time', sa.Time(), server_default=sa.text("'09:00'"), nullable=False),
    sa.Column('threshold_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('horizon_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('recommend_limit', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('daily_digest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=128), nullable=False),
    sa.Column('storage_place_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.String(length=16), server_default=sa.text("'in_stock'"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), server_default=sa.text('1'), nullable=False),
    sa.Column('unit', sa.String(length=16), server_default=sa.text("'шт'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('manufacture_date IS NULL OR expiry_date >= manufacture_date', name='ck_products_expiry_after_manufacture'),
    sa.CheckConstraint('quantity > 0', name='ck_products_quantity_positive'),
    sa.ForeignKeyConstraint(['ingredient_name'], ['ingredients.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_code'], ['product_statuses.code'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_place_id'], ['storage_places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'name', 'expiry_date', name='uq_products_owner_name_expiry')
    )
    op.create_index(op.f('ix_products_expiry_date'), 'products', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_products_ingredient_name'), 'products', ['ingredient_name'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_title', sa.String(length=255), nullable=False),
    sa.Column('ingredient_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_name'], ['ingredients.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_title'], ['recipes.title'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_title', 'ingredient_name')
    )
    op.create_table('recommendation_items',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recipe_title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('covered_weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_title'], ['recipes.title'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'recipe_title')
    )
    op.create_table('notification_items',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_items')
    op.drop_table('recommendation_items')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_products_ingredient_name'), table_name='products')
    op.drop_index(op.f('ix_products_expiry_date'), table_name='products')
    op.drop_table('products')
    op.drop_table('user_settings')
    op.drop_table('storage_places')
    op.drop_table('recommendation_sessions')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ingredients_category_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('product_statuses')
    op.drop_table('categories')
    # ### end Alembic commands ###
