"""remove daily digest

Revision ID: 5951f1115367
Revises: 21bfea8b488f
Create Date: 2026-09-09 10:28:56.741939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5951f1115367'
down_revision: Union[str, None] = '21bfea8b488f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'daily_digest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('daily_digest', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
